---
# tasks file for elasticsearch
#https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz

- name: stat /tmp/elasticsearch-2.3.3.tar.gz
  stat: path=/tmp/elasticsearch-2.3.3.tar.gz
  register: elastic_binary_stat

- name: Downloading Elastic Search For Hadoop
  get_url: url=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz  dest=/tmp/elasticsearch-2.3.3.tar.gz
  when: elastic_binary_stat.stat.exists == False

- name: uncompress file tarball and place in /usr/local/
  command: creates="/usr/local/elasticsearch-2.3.3" tar zxf /tmp/elasticsearch-2.3.3.tar.gz -C /usr/local/

- name: rename file
  command: creates="/usr/local/elasticsearch" mv /usr/local/elasticsearch-2.3.3  /usr/local/elasticsearch

- name: change ownerships file
  command: chown -R hadoop:hadoop  /usr/local/elasticsearch
